-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgl7YcVlYhP/r2eYzn
A7Ur6tPLeRJxC0Qf2Mh7qS4rBdmgCgYIKoZIzj0DAQehRANCAATLd9dj/0mvfawX
NC9ZAJQo2ppoabceoBMsVAkggqXv+5n+kVWaxoCV7p5LXw9Rv5TyGHrYSZPGaxYH
s+EcJHuG
-----END PRIVATE KEY-----